export { default as Process } from "./process"
export { default as Hero } from "./hero"
export { default as AboutUs } from "./about-us"
export { default as BrandsSlider } from "./brandsSlider" 
export { default as Delivery } from "./delivery" 